name: Build and Test
on:
  push:
    branches:
      - 'feature/*'
      - 'patch/*'

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x

      - name: Build
        run: cd app/ && go build -o myapp

      - name: Test
        run:  cd app/ && go test .