name: Build, Test, and Push to Private Registry

on:
  push:
    branches:
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x

      - name: Change to app directory
        run: cd app

      - name: List directory content
        run: ls -l
        
      - name: Build
        run: go build -o myapp

      - name: Test
        run: go test ./...