name: Build Docker Image on Main

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
        NEXUS_DOCKER_URL: nexus.petruska.dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Generate Version
        id: version
        run: echo "VERSION=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Login to Neuxs
        uses: docker/login-action@v3
        with:
          registry: nexus.petruska.dev
          username: ${{ secrets.NEXUS_USER }}
          password: ${{ secrets.NEXUS_PASS }}

      - name: Build Docker image
        run: |
          docker build -t thesis-demoapp:$VERSION .
          docker tag thesis-demoapp:$VERSION $NEXUS_DOCKER_URL/thesis-demoapp:$VERSION
          docker push $NEXUS_DOCKER_URL/thesis-demoapp:$VERSION