name: CI Pipeline for thesis-demo

on:
    push:
        branches:
        - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
        NEXUS_DOCKER_URL: nexus.petruska.dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: Generate Version
        id: semantic_version
        uses: PaulHatch/semantic-version@v5.2.1
        with:
          branch: 'main'
          tag_prefix: "v"
          major_pattern: "breaking:"
          minor_pattern: "feat:"
          version_format: "v${major}.${minor}.${patch}-prerelease${increment}"        
          debug: true

      - name: Login to Neuxs
        uses: docker/login-action@v3
        with:
          registry: nexus.petruska.dev
          username: ${{ secrets.NEXUS_USER }}
          password: ${{ secrets.NEXUS_PASS }}

      - name: Build Docker image
        run: |
          docker build -t thesis-demoapp:${{ steps.semantic_version.outputs.version }} .
          docker tag thesis-demoapp:${{ steps.semantic_version.outputs.version }} $NEXUS_DOCKER_URL/thesis-demoapp:${{ steps.semantic_version.outputs.version }}
          docker push $NEXUS_DOCKER_URL/thesis-demoapp:${{ steps.semantic_version.outputs.version }}

      - name: Create Release
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.semantic_version.outputs.version }}
          release_name: ${{ steps.semantic_version.outputs.version }}
          prerelease: true
