name: Release thesis-demo

on:
  push:
    tags:
      - 'v*'
jobs:
  docker:
    runs-on: ubuntu-latest
    env:
        NEXUS_DOCKER_URL: nexus.petruska.dev
        REPO: thesis-demoapp
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: Set environment variables
        run: |
          cat >> $GITHUB_ENV << EOF
          VERSION=${GITHUB_REF##*/}
          EOF

      - name: Login to Neuxs
        uses: docker/login-action@v3
        with:
          registry: nexus.petruska.dev
          username: ${{ secrets.NEXUS_USER }}
          password: ${{ secrets.NEXUS_PASS }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.NEXUS_DOCKER_URL }}/${{ env.REPO }}:latest,${{ env.NEXUS_DOCKER_URL }}/${{ env.REPO }}:${{ env.VERSION }}