name: Build Docker Image on feature

on:
    push:
        branches:
        - 'feature/*'

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
        NEXUS_DOCKER_URL: nexus.petruska.dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: Generate Version
        id: semantic_version
        uses: PaulHatch/semantic-version@v5.2.1
        with:
          branch: 'feature/*'
          tag_prefix: "v"
          major_pattern: "breaking:"
          minor_pattern: "feat:"
          version_format: "${major}.${minor}.${patch}"          
          debug: true
      - name: Login to Neuxs
        uses: docker/login-action@v3
        with:
          registry: nexus.petruska.dev
          username: ${{ secrets.NEXUS_USER }}
          password: ${{ secrets.NEXUS_PASS }}

      - name: Build Docker image
        run: |
          docker build -t thesis-demoapp:${{ steps.semantic_version.outputs.version }} .
          docker tag thesis-demoapp:${{ steps.semantic_version.outputs.version }} $NEXUS_DOCKER_URL/thesis-demoapp:${{ steps.semantic_version.outputs.version }}
          ##docker push $NEXUS_DOCKER_URL/thesis-demoapp:${{ steps.semantic_version.outputs.version }}
