name: Build Docker Image on feature

on:
    push:
        branches:
        - 'feature/*'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Generate Version
        id: version
        run: echo "VERSION=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t thesis-demoapp:$VERSION .
          docker login -u ${{ secrets.NEXUS_USER }} -p ${{ secrets.NEXUS_PASS }} $NEXUS_DOCKER_URL
          docker tag thesis-demoapp:$VERSION $NEXUS_DOCKER_URL/thesis-demoapp:$VERSION
          docker push $NEXUS_DOCKER_URL/thesis-demoapp:$VERSION